# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

env:
  RootPassword: mypassword

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.2
        
    - name: Set up MySQL
      run: docker pull mysql
    - name: Run MySQL image
      run: docker run --name my-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=$RootPassword -d mysql
      
    - name: Set up Kafka Zookeeper
      run: docker pull confluentinc/cp-zookeeper:7.3.0
    - name: Run Zookeeper
      run: |
        docker run --name zookeeper -p 2181:2181 \
        -e ZOOKEEPER_CLIENT_PORT='2181' \
        -e ZOOKEEPER_TICK_TIME='2000' \
        -d confluentinc/cp-zookeeper:7.3.0
    - name: Set up Kafka Kafka
      run: docker pull confluentinc/cp-kafka:7.3.0
    - name: Run Kafka
      run: |
        docker run --name broker -p 9092:9092 \
        -e KAFKA_BROKER_ID=1 \ 
        -e KAFKA_ZOOKEEPER_CONNECT='zookeeper:2181' \
        -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT \
        -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092 \
        -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
        -e KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1 \
        -e KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1 \
        --link zookeeper \
        -d confluentinc/cp-kafka:7.3.0

    - name: Build with Maven
#       run: mvn clean install
      run: mvn -B package --file customer-service/pom.xml
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
